# Base configuration
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
markdown: kramdown
highlighter: rouge

collections:
  pages:
    output: true
    permalink: /:path/

# Title
name: A Boy and His Beans
subtitle: A collection of jelly bean reviews.

# When using this template with a project page set the baseurl to '/project-name'
# For user/organization pages set this to an empty string
# When working locally use jekyll serve --baseurl '' so that you can view everything at localhost:4000
# See http://jekyllrb.com/docs/github-pages/ for more info
baseurl: '/jellybeans'

# Author/Organization info to be displayed in the templates
author:
  name: Scott Cranfill
  url: https://twitter.com/scott_ish

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl:
logoalt:

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Home
  url: ./
  internal: true
  id: home
- text: About
  url: about/
  internal: true
  id: about
- text: Amazon List
  url: https://www.amazon.com/gp/registry/wishlist/36YXMMNMA3W5D/
  internal: false

# Repo list
# List repos that you would like to appear on the homepage here
repos:
- name: jellybeans
  description: Source code for this site
  url: https://github.com/Scotchester/jellybeans

# Style Variables
brand_color: "rebeccapurple"

# Jekyll plugins
gems:
  - jemoji

# Offline caching
offline_cache: true
cache_name: jellybeans-v1.0
