# Base configuration
exclude:
  - node_modules
  - src
  - test
  - .gitignore
  - CONTRIBUTING.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - package.json
  - postcss.json
  - README.md
  - TERMS.md
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge

# Collections
collections:
  pages:
    output: true
    permalink: /:path/

# Title
title: A Boy and His Beans
description: A collection of jelly bean reviews.

# Author/Organization info to be displayed in the templates
author:
  name: Scott Cranfill
  email: scott@scottcranfill.com
  url: https://twitter.com/scott_ish

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl:
logoalt:

# Navigation
# List links that should appear in the site sidebar here
navigation:
  - label: Home
    path: ./
    internal: true
    slug: home
  - label: About
    path: about/
    internal: true
    slug: about
  - label: Amazon List
    url: https://www.amazon.com/gp/registry/wishlist/36YXMMNMA3W5D/
    internal: false

# Style Variables
brand_color: '#639'

# Jekyll plugins
plugins:
  - jemoji
  - jekyll-feed

# Offline caching
offline_cache: true
cache_name: jellybeans-v1.38
